export const routes = {
    homePage: { path: '/', title: 'Home' },
    loginPage: { path: '/login', title: 'Login' },
    registerPage: { path: '/register', title: 'Register' },
    unauthorized: { path: '/unauthorized', title: 'Unauthorized' },
    protectedPage: { path: '/user', title: 'User Dashboard' },
    adminPage: { path: '/admin', title: 'Admin Dashboard' },
    newOrgPage: { path: '/new-organization', title: 'Add New Organization' },
    existingOrgPage: { path: '/existing-organizations', title: 'Existing Organizations' },
    orgPage: { path: '/organization', title: 'Organization Dashboard' },
    orgAddAgent: { path: '/add-agents', title: 'Add Agents' },
    orgCurrentAgent: { path: '/current-agents', title: 'Current Agents' },
    addNewJob: { path: '/new-job', title: 'New Job'},
    currentJobs: { path: '/current-jobs', title: 'Current Jobs' },
    orgSettings: { path: '/organization-settings', title: 'Organization Settings' },
    agentPage: { path: '/agent', title: 'Agent Dashboard' },
    studentShifts: { path: '/student-shifts', title: 'Student Shifts' },
    studentsList: { path: '/students-list', title: 'Students List' },
    studentApply: { path: '/student-apply', title: 'Student Apply' },
    agentSettings: { path: '/agent-settings', title: 'Agent Settings' },
    adminSettings: { path: '/admin-settings', title: 'Admin Settings'}, 
  };